### ISSUE TITLE
Investigate shared composer cache

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/github-actions-ci-cd#31]
"When running this (ci.yml) in a fork of silverstripe-campaign-admin I saw:"

`Cache hit occurred on the primary key shared-composer-cache, not saving cache.`

Does this mean we share cache even for runs outside the silverstripe organisation? Is that safe?

```
      # This is shared between runs, not just jobs. It means the first time the repo runs the job it'll
      # need to download requirements for the first time, after that it will be plenty quick
      # https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
      - name: Enable shared composer cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer
          key: shared-composer-cache
```

### ACs
- [x] Shared composer cache works
- [x] Ensure there is no security issue
